//install node

//install inquirerer

const inquirer = require('inquirer');
console.log(inquirer);
let fs = require('fs');
//require fs
let questions = [
    {
        type: "input",
        message: "What is your Name?",
        name: "Name"
    },
    {
        type: "input",
        message: "What is your Location?",
        name: "Location"
    },
    {
        type: "input",
        message: "What is your Biography?",
        name: "Biography"
    },
    {
        type: "input",
        message: "What is your LinkedIn?",
        name: "LinkedInURL"
    },
    {
        type: "input",
        message: "What is your Github?",
        name: "GithubURL"
    },
];

inquirer
.prompt(questions, (res) => {
    console.log(res);
})

//process.argv[i] <--- accept inputs from CLI.

//FS.writeFile or appendFile to create an HTML page that will be generated by our thing.

//Make a REALLY basic HTML page for now, with some super simple styling.
//Styling should go in the HEAD of our page.

//Name
//Location
//Biography
//LInkinURL
//GithubURL
//Additional Prompts
