//install node

//install inquirerer

const inquirer = require('inquirer');
console.log(inquirer);
let fs = require('fs');
//require fs

let questions = [
    {
        type: "input",
        message: "What is your Name?",
        name: "Name"
    },
    {
        type: "input",
        message: "What is your Location?",
        name: "Location"
    },
    {
        type: "input",
        message: "What is your Biography?",
        name: "Biography"
    },
    {
        type: "input",
        message: "What is your LinkedIn?",
        name: "LinkedInURL"
    },
    {
        type: "input",
        message: "What is your Github?",
        name: "GithubURL"
    },
];

inquirer
.prompt(questions)
    .then((response) => {
        console.log(response);
        let page = `<!DOCTYPE html>
    <html lang="en-us">

    <head>
    <meta charset="UTF-8" />
    <title>Portfolio Gen</title>
    </head>

    <body>
   Hi: my name is: ${response.Name}
   I'm at ${response.Location}
   My biography is ${response.Biography}
   My LinkedIN is ${response.LinkedInURL}
   my Github is ${response.GithubURL}
    </body>

    </html>`
        fs.writeFile('index.html', page, (err) => {
            err ? console.log(err) : console.log("It worked!");
        });
});




//FS.writeFile or appendFile to create an HTML page that will be generated by our thing.

//Make a REALLY basic HTML page for now, with some super simple styling.
//Styling should go in the HEAD of our page.

//Name
//Location
//Biography
//LInkinURL
//GithubURL
//Additional Prompts
